
import React from 'react';

export const Icons = {
  Home: () => <i className="fas fa-home"></i>,
  Search: () => <i className="fas fa-search"></i>,
  User: () => <i className="fas fa-user"></i>,
  Moon: () => <i className="fas fa-moon"></i>,
  Sun: () => <i className="fas fa-sun"></i>,
  Chat: () => <i className="fas fa-comments"></i>,
  Money: () => <i className="fas fa-wallet"></i>,
  GradCap: () => <i className="fas fa-graduation-cap"></i>,
  Briefcase: () => <i className="fas fa-briefcase"></i>,
  MapMarker: () => <i className="fas fa-map-marker-alt"></i>,
  Globe: () => <i className="fas fa-globe"></i>,
  Robot: () => <i className="fas fa-robot"></i>,
  Check: () => <i className="fas fa-check-circle"></i>,
  Lock: () => <i className="fas fa-lock"></i>,
  Unlock: () => <i className="fas fa-unlock"></i>,
  Clock: () => <i className="fas fa-clock"></i>,
  Bank: () => <i className="fas fa-university"></i>,
  Exclamation: () => <i className="fas fa-exclamation-circle"></i>,
  Stripe: () => <i className="fab fa-stripe text-indigo-500 text-3xl"></i>,
  Heart: () => <i className="fas fa-heart"></i>,
  Comment: () => <i className="far fa-comment"></i>,
  Share: () => <i className="far fa-paper-plane"></i>,
  Repost: () => <i className="fas fa-retweet"></i>,
  Plus: () => <i className="fas fa-plus"></i>,
  Settings: () => <i className="fas fa-cog"></i>,
  Key: () => <i className="fas fa-key"></i>,
  Admission: () => <i className="fas fa-clipboard-list"></i>,
  Bell: () => <i className="fas fa-bell"></i>,
  Edit: () => <i className="fas fa-edit"></i>,
  Trash: () => <i className="fas fa-trash-alt"></i>,
  Ellipsis: () => <i className="fas fa-ellipsis-h"></i>,
  EllipsisV: () => <i className="fas fa-ellipsis-v"></i>,
  Users: () => <i className="fas fa-users"></i>,
  Shield: () => <i className="fas fa-shield-alt"></i>,
};
